language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
script:
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install unittest2; fi
- wget http://sgjp.pl/morfeusz/morfeusz-siat/morfeusz-linux64-20080205.tar.bz2
- tar -xvf morfeusz-linux64-20080205.tar.bz2
- LD_LIBRARY_PATH=$PWD python tests.py

# vim:ts=2 sts=2 sw=2 et
